name: CI
on: [push, pull_request]

jobs:
  shellcheck:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - run: nix-env -f ./nix/pkgs.nix -iA shellcheck
      - run: shellcheck -x -s bash ./src/main.sh
  sync-dry-run:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - run: |
          nix-shell --pure --command "bash ./src/main.sh $GITHUB_TOKEN dry-run"
        env: 
          GITHUB_TOKEN: ${{ secrets.SOHOSAI_LABELS_TOKEN }}
  nixpkgs-fmt:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - run: nix-env -f ./nix/pkgs.nix -iA nixpkgs-fmt
      - run: |
          find . -name '*.nix' ! -name 'node2nix-composition.nix' ! -name 'node-env.nix' ! -name 'node-packages.nix' -print0 | while IFS= read -r -d '' file; do
            nixpkgs-fmt --check "$file"
          done
  dhall-lint:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - run: nix-env -f ./nix/pkgs.nix -iA dhall
      - run: |
          find . -name '*.dhall' -print0 | while IFS= read -r -d '' file; do
            dhall lint --check "$file"
          done
  dhall-format:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - run: nix-env -f ./nix/pkgs.nix -iA dhall
      - run: |
          find . -name '*.dhall' -print0 | while IFS= read -r -d '' file; do
            dhall format --check "$file"
          done
  actionlint:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - run: nix-env -f ./nix/pkgs.nix -iA actionlint
      - run: actionlint
