name: CI
on: [push, pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - run: nix-env -f ./nix/pkgs.nix -iA shellcheck
      - run: shellcheck -x -s bash ./src/main.sh
  sync-dry-run:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - run: |
          nix-shell --command "bash ./src/main.sh $GITHUB_TOKEN dry-run"
        env: 
          GITHUB_TOKEN: ${{ secrets.SOHOSAI_LABELS_TOKEN }}
  nixpkgs-fmt:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - run: nix-env -f ./nix/pkgs.nix -iA nixpkgs-fmt
      - run: nixpkgs-fmt --check $(find . -name '*.nix' ! -name 'github-label-sync.nix' ! -name 'node-env.nix' ! -name 'node-packages.nix')
