name: CI
on: [push, pull_request]

jobs:
  shellcheck:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - run: nix-env -f ./nix/pkgs.nix -iA shellcheck
      - run: shellcheck -x -s bash ./src/main.sh
  sync-dry-run:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - run: |
          nix-shell --command "bash ./src/main.sh $GITHUB_TOKEN dry-run"
        env: 
          GITHUB_TOKEN: ${{ secrets.SOHOSAI_LABELS_TOKEN }}
  nixpkgs-fmt:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - run: nix-env -f ./nix/pkgs.nix -iA nixpkgs-fmt
      - run: nixpkgs-fmt --check "$(find . -name '*.nix' ! -name 'github-label-sync.nix' ! -name 'node-env.nix' ! -name 'node-packages.nix')"
  dhall-lint:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - run: nix-env -f ./nix/pkgs.nix -iA dhall
      - run: dhall lint --check "$(find . -name '*.dhall')"
  dhall-format:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - run: nix-env -f ./nix/pkgs.nix -iA dhall
      - run: dhall format --check "$(find . -name '*.dhall')"
  actionlint:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12.0]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - run: nix-env -f ./nix/pkgs.nix -iA actionlint
      - run: actionlint
