name: Apply Demo
on: [workflow_dispatch]

jobs:
  apply:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            sandbox = true
      - name: Apply
        run: |
          nix-shell --pure --command "bash src/main.sh $GITHUB_TOKEN dev" ./shell.nix
        env:
          GITHUB_TOKEN: ${{ secrets.SOHOSAI_LABELS_TOKEN }}
