name: Apply Main
on:
  push:
    branches:
      - main

jobs:
  apply:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - if: runner.os == 'macOS'
        run: |
          brew install bash
          sudo bash -c 'echo /usr/local/bin/bash >> /etc/shells'
          chsh -s /usr/local/bin/bash
      - uses: cachix/install-nix-action@v22
      - name: Apply
        run: |
          nix-shell --pure --command "bash src/main.sh $GITHUB_TOKEN prod"
        env:
          GITHUB_TOKEN: ${{ secrets.SOHOSAI_LABELS_TOKEN }}
