name: Apply Main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - name: Apply
        run: |
          nix-shell --command "bash src/main.sh $GITHUB_SECRET prod"
        env:
          GITHUB_SECRET: ${{ secrets.GITHUB_SECRET }}
